{% set version = "2021.6.0" %}

package:
  name: s3fs
  version: {{ version }}

source:
  fn: s3fs-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/s3fs/s3fs-{{ version }}.tar.gz
  sha256: 53790061e220713918602c1f110e6a84d6e3e22aaba27b8e134cc56a3ab6284c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip

  run:
    - python >=3.6
    - aiobotocore
    - botocore
    - fsspec ==2021.06.0


test:
  requires:
    - pip
  imports:
    - s3fs
  commands:
    - pip check

about:
  home: http://s3fs.readthedocs.io/en/latest/
  license: BSD-3-Clause
  summary: Convenient Filesystem interface over S3
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - koverholt
    - tomaugspurger
