{% set version = "2022.1.0" %}

package:
  name: s3fs
  version: {{ version }}

source:
  fn: s3fs-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/s3fs/s3fs-{{ version }}.tar.gz
  sha256: 6bafc1f6b4e935ea59512c0f38d5cb9c299dbbfe738e40c3d1de8f67b4ee1fd4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip

  run:
    - python >=3.6
    - aiobotocore ==2.0.1
    - botocore
    - fsspec ==2021.11.1
    - aiohttp >=3.7.1,<4


test:
  requires:
    - pip
  imports:
    - s3fs
  commands:
    - pip check

about:
  home: http://s3fs.readthedocs.io/en/latest/
  license: BSD-3-Clause
  summary: Convenient Filesystem interface over S3
  license_file: LICENSE.txt
  dev_url: https://github.com/dask/s3fs
  doc_url: https://s3fs.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - tomaugspurger
